# -*- coding: utf-8 -*-
"""IDX Data Science - Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m85zTEJ8_gE28uyR_0vOUPBC9hPl_mpd

# Loan Data Analysis

# 🧭 Business Understanding

**Project:** _Credit Risk Analysis & Predictive Modeling — Lending Club Loan Data_

**Client Objective:** _Membangun insight dan model prediksi risiko kredit untuk mendukung keputusan persetujuan pinjaman dan manajemen portofolio investasi._

## 🎯 Tujuan Bisnis

Sebagai perusahaan _peer-to-peer lending_, Lending Club berperan sebagai perantara antara pemberi pinjaman (_investor_) dan peminjam (_borrower_). Dalam konteks ini, tujuan utama bisnis adalah **mengoptimalkan keseimbangan antara pertumbuhan pinjaman dan pengendalian risiko gagal bayar (default)**.

Secara spesifik, proyek ini bertujuan untuk:

1. **Mengidentifikasi faktor-faktor risiko kredit** berdasarkan data historis pinjaman yang diterima dan ditolak.
2. **Membangun model prediktif risiko kredit** untuk memperkirakan kemungkinan gagal bayar sejak tahap aplikasi.
3. **Mendukung tim risiko dan keuangan** dalam pengambilan keputusan berbasis data:
   - Menentukan kriteria persetujuan pinjaman yang optimal.
   - Menetapkan bunga pinjaman berbasis risiko (_risk-based pricing_).
   - Menyusun strategi mitigasi risiko yang proaktif.

## 💡 Nilai Bisnis (Business Value)

Melalui analisis data dan visualisasi, proyek ini akan membantu perusahaan untuk:

- **Menekan tingkat gagal bayar** dengan mengidentifikasi calon peminjam berisiko tinggi.
- **Meningkatkan profitabilitas portofolio pinjaman** dengan penetapan bunga yang lebih akurat.
- **Mengoptimalkan strategi penyaluran pinjaman** dengan memahami tren demografis, tujuan pinjaman, dan perilaku pembayaran.

# 💾 Data Description

## ➤ Field Description

| Field                       | Description                                                                                                                                                                                                        |
| --------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| acceptD                     | The date which the borrower accepted  the offer                                                                                                                                                                    |
| accNowDelinq                | The number of accounts on which the borrower is now delinquent.                                                                                                                                                    |
| accOpenPast24Mths           | Number of trades opened in past 24 months.                                                                                                                                                                         |
| addrState                   | The state provided by the borrower in the loan application                                                                                                                                                         |
| all_util                    | Balance to credit limit on all trades                                                                                                                                                                              |
| annual_inc_joint            | The combined self-reported annual income provided by the co-borrowers during registration                                                                                                                          |
| annualInc                   | The self-reported annual income provided by the borrower during registration.                                                                                                                                      |
| application_type            | Indicates whether the loan is an individual application or a joint application with two co-borrowers                                                                                                               |
| avg_cur_bal                 | Average current balance of all accounts                                                                                                                                                                            |
| bcOpenToBuy                 | Total open to buy on revolving bankcards.                                                                                                                                                                          |
| bcUtil                      | Ratio of total current balance to high credit/credit limit for all bankcard accounts.                                                                                                                              |
| chargeoff_within_12_mths    | Number of charge-offs within 12 months                                                                                                                                                                             |
| collections_12_mths_ex_med  | Number of collections in 12 months excluding medical collections                                                                                                                                                   |
| creditPullD                 | The date LC pulled credit for this loan                                                                                                                                                                            |
| delinq2Yrs                  | The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years                                                                                                       |
| delinqAmnt                  | The past-due amount owed for the accounts on which the borrower is now delinquent.                                                                                                                                 |
| desc                        | Loan description provided by the borrower                                                                                                                                                                          |
| dti                         | A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income.           |
| dti_joint                   | A ratio calculated using the co-borrowers' total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the co-borrowers' combined self-reported monthly income |
| earliestCrLine              | The date the borrower's earliest reported credit line was opened                                                                                                                                                   |
| effective_int_rate          | The effective interest rate is equal to the interest rate on a Note reduced by Lending Club's estimate of the impact of uncollected interest prior to charge off.                                                  |
| emp_title                   | The job title supplied by the Borrower when applying for the loan.\*                                                                                                                                               |
| empLength                   | Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.                                                                                  |
| expD                        | The date the listing will expire                                                                                                                                                                                   |
| expDefaultRate              | The expected default rate of the loan.                                                                                                                                                                             |
| ficoRangeHigh               | The upper boundary range the borrower’s FICO at loan origination belongs to.                                                                                                                                       |
| ficoRangeLow                | The lower boundary range the borrower’s FICO at loan origination belongs to.                                                                                                                                       |
| fundedAmnt                  | The total amount committed to that loan at that point in time.                                                                                                                                                     |
| grade                       | LC assigned loan grade                                                                                                                                                                                             |
| homeOwnership               | The home ownership status provided by the borrower during registration. Our values are: RENT, OWN, MORTGAGE, OTHER.                                                                                                |
| id                          | A unique LC assigned ID for the loan listing.                                                                                                                                                                      |
| il_util                     | Ratio of total current balance to high credit/credit limit on all install acct                                                                                                                                     |
| ils_exp_d                   | wholeloan platform expiration date                                                                                                                                                                                 |
| initialListStatus           | The initial listing status of the loan. Possible values are – W, F                                                                                                                                                 |
| inq_fi                      | Number of personal finance inquiries                                                                                                                                                                               |
| inq_last_12m                | Number of credit inquiries in past 12 months                                                                                                                                                                       |
| inqLast6Mths                | The number of inquiries in past 6 months (excluding auto and mortgage inquiries)                                                                                                                                   |
| installment                 | The monthly payment owed by the borrower if the loan originates.                                                                                                                                                   |
| intRate                     | Interest Rate on the loan                                                                                                                                                                                          |
| isIncV                      | Indicates if income was verified by LC, not verified, or if the income source was verified                                                                                                                         |
| listD                       | The date which the borrower's application was listed on the platform.                                                                                                                                              |
| loanAmnt                    | The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value.                                       |
| max_bal_bc                  | Maximum current balance owed on all revolving accounts                                                                                                                                                             |
| memberId                    | A unique LC assigned Id for the borrower member.                                                                                                                                                                   |
| mo_sin_old_rev_tl_op        | Months since oldest revolving account opened                                                                                                                                                                       |
| mo_sin_rcnt_rev_tl_op       | Months since most recent revolving account opened                                                                                                                                                                  |
| mo_sin_rcnt_tl              | Months since most recent account opened                                                                                                                                                                            |
| mortAcc                     | Number of mortgage accounts.                                                                                                                                                                                       |
| msa                         | Metropolitan Statistical Area of the borrower.                                                                                                                                                                     |
| mths_since_last_major_derog | Months since most recent 90-day or worse rating                                                                                                                                                                    |
| mths_since_oldest_il_open   | Months since oldest bank installment account opened                                                                                                                                                                |
| mths_since_rcnt_il          | Months since most recent installment accounts opened                                                                                                                                                               |
| mthsSinceLastDelinq         | The number of months since the borrower's last delinquency.                                                                                                                                                        |
| mthsSinceLastRecord         | The number of months since the last public record.                                                                                                                                                                 |
| mthsSinceMostRecentInq      | Months since most recent inquiry.                                                                                                                                                                                  |
| mthsSinceRecentBc           | Months since most recent bankcard account opened.                                                                                                                                                                  |
| mthsSinceRecentLoanDelinq   | Months since most recent personal finance delinquency.                                                                                                                                                             |
| mthsSinceRecentRevolDelinq  | Months since most recent revolving delinquency.                                                                                                                                                                    |
| num_accts_ever_120_pd       | Number of accounts ever 120 or more days past due                                                                                                                                                                  |
| num_actv_bc_tl              | Number of currently active bankcard accounts                                                                                                                                                                       |
| num_actv_rev_tl             | Number of currently active revolving trades                                                                                                                                                                        |
| num_bc_sats                 | Number of satisfactory bankcard accounts                                                                                                                                                                           |
| num_bc_tl                   | Number of bankcard accounts                                                                                                                                                                                        |
| num_il_tl                   | Number of installment accounts                                                                                                                                                                                     |
| num_op_rev_tl               | Number of open revolving accounts                                                                                                                                                                                  |
| num_rev_accts               | Number of revolving accounts                                                                                                                                                                                       |
| num_rev_tl_bal_gt_0         | Number of revolving trades with balance >0                                                                                                                                                                         |
| num_sats                    | Number of satisfactory accounts                                                                                                                                                                                    |
| num_tl_120dpd_2m            | Number of accounts currently 120 days past due (updated in past 2 months)                                                                                                                                          |
| num_tl_30dpd                | Number of accounts currently 30 days past due (updated in past 2 months)                                                                                                                                           |
| num_tl_90g_dpd_24m          | Number of accounts 90 or more days past due in last 24 months                                                                                                                                                      |
| num_tl_op_past_12m          | Number of accounts opened in past 12 months                                                                                                                                                                        |
| open_acc_6m                 | Number of open trades in last 6 months                                                                                                                                                                             |
| open_il_12m                 | Number of installment accounts opened in past 12 months                                                                                                                                                            |
| open_il_24m                 | Number of installment accounts opened in past 24 months                                                                                                                                                            |
| open_il_6m                  | Number of currently active installment trades                                                                                                                                                                      |
| open_rv_12m                 | Number of revolving trades opened in past 12 months                                                                                                                                                                |
| open_rv_24m                 | Number of revolving trades opened in past 24 months                                                                                                                                                                |
| openAcc                     | The number of open credit lines in the borrower's credit file.                                                                                                                                                     |
| pct_tl_nvr_dlq              | Percent of trades never delinquent                                                                                                                                                                                 |
| percentBcGt75               | Percentage of all bankcard accounts > 75% of limit.                                                                                                                                                                |
| pub_rec_bankruptcies        | Number of public record bankruptcies                                                                                                                                                                               |
| pubRec                      | Number of derogatory public records                                                                                                                                                                                |
| purpose                     | A category provided by the borrower for the loan request.                                                                                                                                                          |
| reviewStatus                | The status of the loan during the listing period. Values: APPROVED, NOT_APPROVED.                                                                                                                                  |
| reviewStatusD               | The date the loan application was reviewed by LC                                                                                                                                                                   |
| revolBal                    | Total credit revolving balance                                                                                                                                                                                     |
| revolUtil                   | Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit.                                                                                         |
| serviceFeeRate              | Service fee rate paid by the investor for this loan.                                                                                                                                                               |
| subGrade                    | LC assigned loan subgrade                                                                                                                                                                                          |
| tax_liens                   | Number of tax liens                                                                                                                                                                                                |
| term                        | The number of payments on the loan. Values are in months and can be either 36 or 60.                                                                                                                               |
| title                       | The loan title provided by the borrower                                                                                                                                                                            |
| tot_coll_amt                | Total collection amounts ever owed                                                                                                                                                                                 |
| tot_cur_bal                 | Total current balance of all accounts                                                                                                                                                                              |
| tot_hi_cred_lim             | Total high credit/credit limit                                                                                                                                                                                     |
| total_bal_il                | Total current balance of all installment accounts                                                                                                                                                                  |
| total_cu_t                  | Number of finance trades                                                                                                                                                                                           |
| total_il_high_credit_limit  | Total installment high credit/credit limit                                                                                                                                                                         |
| total_rev_hi_lim            | Total revolving high credit/credit limit                                                                                                                                                                           |
| totalAcc                    | The total number of credit lines currently in the borrower's credit file                                                                                                                                           |
| totalBalExMort              | Total credit balance excluding mortgage                                                                                                                                                                            |
| totalBcLimit                | Total bankcard high credit/credit limit                                                                                                                                                                            |
| url                         | URL for the LC page with listing data.                                                                                                                                                                             |
| verified_status_joint       | Indicates if the co-borrowers' joint income was verified by LC, not verified, or if the income source was verified                                                                                                 |
| zip_code                    | The first 3 numbers of the zip code provided by the borrower in the loan application.                                                                                                                              |

## ➤ Dataframe
"""

!pip install pandas scikit-learn numpy hvplot plotly -q

import os

import numpy as np
import pandas as pd
import seaborn as sns
import urllib

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)
pd.options.plotting.backend = "hvplot"

os.makedirs("data", exist_ok=True)

url = "https://rakamin-lms.s3.ap-southeast-1.amazonaws.com/vix-assets/idx-partners/loan_data_2007_2014.csv"
(
    urllib.request.urlretrieve(url, "data/data.csv")
    if not os.path.exists("data/data.csv")
    else print("File already exists.")
)

df = pd.read_csv("data/data.csv", index_col=0, low_memory=False)
df.head()

df.info()

df.describe()

df = df.dropna(axis=1, how="all")
df.describe()

"""# 🔍 Exploratory Data Analysis

- Memahami kualitas data, distribusi fitur utama, hubungan antar fitur, dan insight awal yang relevan untuk pemodelan risiko kredit dan visualisasi di Tableau.

## ✅️ Distribusi Variabel Numerik dan Categorical

## ✅️ Loan Status
"""

df["loan_status"].value_counts()

df["loan_status"] = df["loan_status"].replace(
    {
        "Does not meet the credit policy. Status:Fully Paid": "Fully Paid",
        "Does not meet the credit policy. Status:Charged Off": "Charged Off",
    }
)

import plotly.express as px

loan_status_counts = df["loan_status"].value_counts().reset_index()
loan_status_counts.columns = ["loan_status", "count"]

fig = px.bar(
    loan_status_counts,
    x="loan_status",
    y="count",
    title="Loan Status Counts",
    labels={"loan_status": "Loan Status", "count": "Count"},
    color="loan_status",
)


fig.update_layout(
    xaxis_title="Loan Status",
    yaxis_title="Count",
    xaxis_tickangle=-45,
    width=500,
    height=500,
)

fig.show()

sns.set_theme(font_scale=0.6)
sns.heatmap(
    df.select_dtypes(np.number).corr(),
    cmap="coolwarm",
    linecolor="black",
    linewidth=0.7,
)

"""## ✅️ Loan Amount & Installment

"""

import plotly.express as px

installment = px.histogram(
    df,
    x="installment",
    color="loan_status",
    nbins=30,
    opacity=0.75,
    title="Installment by Loan Status",
    labels={"installment": "Installment", "count": "Counts"},
)

loan_amnt = px.histogram(
    df,
    x="loan_amnt",
    color="loan_status",
    nbins=30,
    opacity=0.75,
    title="Loan Amount by Loan Status",
    labels={"loan_amnt": "Loan Amount", "count": "Counts"},
)

installment.show()
loan_amnt.show()

df.groupby(by="loan_status")[["loan_amnt", "installment"]].mean()

"""- **Bigger Loans = Bigger Risks**
  Peminjam dengan **pinjaman lebih besar** (loan amount tinggi) cenderung lebih berisiko untuk **gagal bayar**. Sebagian besar peminjam dalam kategori **Late** atau **Charged Off** memiliki pinjaman yang lebih besar dibandingkan mereka yang **Fully Paid**.

- **Higher Installments = Greater Risk of Missed Payments**
  **Cicilan bulanan lebih tinggi** berarti beban lebih berat bagi peminjam. Ini memicu peningkatan **keterlambatan pembayaran** dan kemungkinan **default**. Penting untuk memantau peminjam dengan cicilan yang melebihi rata-rata.

- **Grace Period = Time Bomb?**
  Meskipun peminjam yang berada dalam **Grace Period** belum gagal bayar, dengan **pinjaman dan cicilan tertinggi**, mereka **berisiko tinggi** untuk gagal bayar di masa depan. Mereka perlu dipantau lebih ketat karena jika tidak mampu melanjutkan pembayaran, mereka bisa segera beralih ke status **Late** atau **Charged Off**.

## ✅️ Grade & Sub-Grade
"""

print(f"GRADE unique: {sorted(df.grade.unique())}")
print(f"SUB_GRADE unique: {sorted(df.sub_grade.unique())}")

df.groupby([
    'sub_grade', 'loan_status']).size().reset_index(name='count')

fig = px.histogram(
    df.sort_values(by="sub_grade"),
    x="sub_grade",
    color="loan_status",
    title="Loan Status by Sub-Grade",
    labels={"sub_grade": "Sub-Grade", "loan_status": "Loan Status"},
    barmode="stack",
)

fig.update_layout(
    xaxis_tickangle=45,
    xaxis_title="Subgrade",
    yaxis_title="Count",
)

fig.show()

"""**Grade tinggi** cenderung memiliki lebih banyak pinjaman yang terlunasi, sementara **grade rendah** menunjukkan risiko lebih tinggi dengan banyak pinjaman yang gagal bayar atau terlambat.

---

1. **Dominasi "Fully Paid"**
   Sebagian besar pinjaman di setiap grade sudah dilunasi dengan baik. Misalnya, di grade `A1`, hampir **50%** pinjaman sudah dilunasi sepenuhnya.

2. **Pinjaman "Current" Masih Tinggi**
   Status **"Current"** (pinjaman berjalan) mendominasi hampir semua grade, menunjukkan banyak peminjam yang membayar tepat waktu.

3. **Risiko Gagal Bayar pada Grade Rendah**
   Di grade rendah seperti `G1` dan `F1`, jumlah pinjaman yang **"Charged Off"** lebih tinggi, mencerminkan risiko gagal bayar yang lebih besar.

4. **Terlambat (Late) Lebih Banyak di Grade Rendah dan Menengah**
   Meskipun lebih sering di grade rendah, status **"Late (31-120 days)"** mulai meningkat di grade menengah, seperti `D1` dan `C1`.

5. **"In Grace Period" Ada di Semua Grade**
   Meskipun jumlahnya kecil, hampir semua grade menunjukkan ada peminjam yang dalam periode tenggang, menandakan potensi penundaan pembayaran.

## ✅️ Term, Home Ownership, Verification Status & Purpose
"""

df['home_ownership'].value_counts()

df['home_ownership'] = df['home_ownership'].replace({"NONE": "OTHER", "ANY": "OTHER"})

term_dist = df.groupby(['term', 'loan_status']).size().reset_index(name='count')
homeownership_dist = df.groupby(['home_ownership', 'loan_status']).size().reset_index(name='count')
verification_dist = df.groupby(['verification_status', 'loan_status']).size().reset_index(name='count')
purpose_dist = df.groupby(['purpose', 'loan_status']).size().reset_index(name='count')

fig_term = px.bar(term_dist, x='term', y='count', color='loan_status',
                  title="Distribusi Term Pinjaman Berdasarkan Loan Status",
                  labels={'count': 'Jumlah Pinjaman', 'term': 'Term Pinjaman'},
                  color_discrete_sequence=px.colors.qualitative.Set1)
fig_term.show()

fig_homeownership = px.bar(homeownership_dist, x='home_ownership', y='count', color='loan_status',
                           title="Distribusi Kepemilikan Rumah Berdasarkan Loan Status",
                           labels={'count': 'Jumlah Pinjaman', 'home_ownership': 'Kepemilikan Rumah'},
                           color_discrete_sequence=px.colors.qualitative.Set2)
fig_homeownership.show()

fig_verification = px.bar(verification_dist, x='verification_status', y='count', color='loan_status',
                          title="Distribusi Status Verifikasi Berdasarkan Loan Status",
                          labels={'count': 'Jumlah Pinjaman', 'verification_status': 'Status Verifikasi'},
                          color_discrete_sequence=px.colors.qualitative.Set3)
fig_verification.show()

fig_purpose = px.bar(purpose_dist, x='purpose', y='count', color='loan_status',
                     title="Distribusi Tujuan Pinjaman Berdasarkan Loan Status",
                     labels={'count': 'Jumlah Pinjaman', 'purpose': 'Tujuan Pinjaman'},
                     color_discrete_sequence=px.colors.qualitative.Set1)
fig_purpose.show()

"""* **60-month loans** = lebih “riskier” ✅
* **RENT** > risiko gagal bayar daripada **OWN/MORTGAGE** 🏠
* **Verified borrower** = lebih aman 💳
* **Small business & debt consolidation** = rawan gagal bayar 📉

---

**1. Term Pinjaman (36 vs 60 months)**

* **36 months** mendominasi volume pinjaman dan pembayaran penuh: 152.890 Fully Paid vs 33.837 pada 60 months.
* Risiko **Charged Off** relatif lebih tinggi pada 60 months: 15.132 vs 28.104 pada 36 months, tetapi secara proporsi, 60 months lebih “riskier” karena total pinjaman lebih kecil.
  
  **💡 Insight:** Pinjaman jangka panjang (60 months) cenderung lebih berisiko meski volumenya lebih kecil.

---

**2. Kepemilikan Rumah (Home Ownership)**

* **RENT** dan **MORTGAGE** mendominasi pinjaman.
* Proporsi **Charged Off** lebih tinggi pada peminjam **RENT** dibanding pemilik rumah (OWN/MORTGAGE).
  
  **💡 Insight:** Peminjam yang menyewa rumah lebih rawan gagal bayar dibanding pemilik rumah.

---

**3. Status Verifikasi**

* **Verified** dan **Source Verified** menunjukkan tingkat pembayaran penuh (Fully Paid) lebih tinggi dibanding **Not Verified**.
* Proporsi **Charged Off** lebih tinggi pada **Not Verified** (12.135 vs 18.459 pada Verified).
  
  **💡 Insight:** Verifikasi identitas berperan signifikan dalam menurunkan risiko gagal bayar.

---

**4. Tujuan Pinjaman (Purpose)**

* **Debt Consolidation** dan **Credit Card** adalah tujuan pinjaman paling populer.
* Pinjaman **small_business** dan **debt_consolidation** memiliki risiko **Charged Off** relatif tinggi dibanding tujuan lain.
* Tujuan **educational**, **renewable_energy**, dan **vacation** menunjukkan default minimal.
  
  **💡 Insight:** Tujuan pinjaman berisiko tinggi terkait usaha kecil dan konsolidasi utang, sementara tujuan pribadi/edukasi relatif aman.

# 🛠️ Data Preprocessing
"""

df['issue_d'] = pd.to_datetime(df['issue_d'], format='%b-%y', errors='coerce')
df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'], format='%b-%y', errors='coerce')
df['next_pymnt_d'] = pd.to_datetime(df['next_pymnt_d'], format='%b-%y', errors='coerce')
df['last_credit_pull_d'] = pd.to_datetime(df['last_credit_pull_d'], format='%b-%y', errors='coerce')
df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], format='%b-%y', errors='coerce')

categorical_cols = df.select_dtypes(include=['object']).columns
categorical_cols

from sklearn.calibration import LabelEncoder

label_encoder = {}
for col in categorical_cols:
    label_encoder[col] = LabelEncoder()
    df[col] = label_encoder[col].fit_transform(df[col])

import plotly.graph_objects as go

correlation_data = df.select_dtypes(np.number).corr()['loan_status'].drop('loan_status').sort_values()

fig = go.Figure()

fig.add_trace(go.Bar(
    y=correlation_data.index,
    x=correlation_data.values,
    orientation='h',
    marker=dict(color=correlation_data.values, colorscale='Viridis', colorbar=dict(title="Correlation")),
))

fig.update_layout(
    title="Correlation between Loan Status and Numeric Features",
    xaxis_title="Correlation",
    yaxis_title="Numerical Features",
    height=600,
    width=800,
    template="plotly_white"
)

fig.show()

correlation_data.sort_values(ascending=False)

from sklearn.model_selection import train_test_split

# hapus fitur yang bersifat muncul setelah 'target' didapatkan
selected_feature = [
    "loan_amnt",
    "funded_amnt",
    "funded_amnt_inv",
    "int_rate",
    "installment",
    "annual_inc",
    "dti",
    "tot_cur_bal",
    "tot_coll_amt",
    "total_rev_hi_lim",
    "revol_bal",
    "revol_util",
    "total_acc",
    "open_acc",
    "acc_now_delinq",
    "delinq_2yrs",
    "inq_last_6mths",
    "pub_rec",
    "emp_length",
    "emp_title",
    "purpose",
    "title",
    "home_ownership",
    "verification_status",
    "application_type",
    "term",
    "addr_state",
    "zip_code",
    "grade",
    "sub_grade",
    "initial_list_status",
    "mths_since_last_delinq",
    "mths_since_last_major_derog",
]

X = df[selected_feature]
y = df["loan_status"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train, y_train)

from sklearn.metrics import classification_report, accuracy_score

y_pred = rf.predict(X_test)
print("\nAkurasi Model:")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

